#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#ffbd5e'
    background = 'transparent'
    # template = '{{ .FormattedMs }}'
    template = '{{ if .SSHSession }}󰣀 {{ end }}'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#5ea1ff'
    background = 'transparent'
    # template = '{{ .FormattedMs }}'
    template = '{{ .HostName }}'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#ff5ea0'
    background = 'transparent'
    template = ' 󰄾 '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = '#5eff6c'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#7b8496'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <#ffbd5e>{{ if gt .Behind 0 }}󰛀{{ end }}{{ if gt .Ahead 0 }}󰛃{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true


[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#ffbd5e'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}#ff6e5e{{end}}",
      "{{if eq .Code 0}}#f1ff5e{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}#ff6e5e{{end}}",
    "{{if eq .Code 0}}#f1ff5e{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = '#f1ff5e'
  background = 'transparent'
  template = '❯❯ '

